##### PATH SETUP #####

# Base paths
export PATH="$HOME/bin:/usr/local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Homebrew (Apple Silicon)
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"

# PostgreSQL 15 (Homebrew)
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"

# Rust (cargo)
export PATH="$HOME/.cargo/bin:$PATH"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
[[ ":$PATH:" != *":$PNPM_HOME:"* ]] && export PATH="$PNPM_HOME:$PATH"

# Google Cloud SDK
[[ -f "$HOME/Desktop/google-cloud-sdk/path.zsh.inc" ]] && source "$HOME/Desktop/google-cloud-sdk/path.zsh.inc"
[[ -f "$HOME/Desktop/google-cloud-sdk/completion.zsh.inc" ]] && source "$HOME/Desktop/google-cloud-sdk/completion.zsh.inc"

##### NVM #####

export NVM_DIR="${XDG_CONFIG_HOME:-$HOME/.nvm}"
[[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"

##### RUBY (chruby) #####

if [ -f /opt/homebrew/opt/chruby/share/chruby/chruby.sh ]; then
    source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
    source /opt/homebrew/opt/chruby/share/chruby/auto.sh
    chruby ruby-3.1.3
fi

##### GPG #####
export GPG_TTY=$(tty)

##### OH-MY-ZSH #####

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="af-magic"
plugins=(git)
[ -f "$ZSH/oh-my-zsh.sh" ] && source "$ZSH/oh-my-zsh.sh"

##### CUSTOM ALIASES (optional example) #####

# alias zshconfig="code ~/.zshrc"
# alias ohmyzsh="code ~/.oh-my-zsh"

##### OTHER CONFIG OPTIONS (uncomment as needed) #####

# Enable command auto-correction
# ENABLE_CORRECTION="true"

# Enable red dots while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Use case-sensitive completion
# CASE_SENSITIVE="true"

# Use hyphen-insensitive completion (requires CASE_SENSITIVE to be false)
# HYPHEN_INSENSITIVE="true"

# Disable terminal title auto-setting
# DISABLE_AUTO_TITLE="true"

# Disable untracked files dirty check in Git
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Set preferred editor
# export EDITOR="code"

# History timestamp format
# HIST_STAMPS="yyyy-mm-dd"